fiis_segments = {
    'CXAG11': 'Agências Bancárias',
    'TVRI11': 'Agências Bancárias',
    'BNFS11': 'Agências Bancárias',
    'BBRC11': 'Agências Bancárias',
    'MALL11': 'Shoppings',
    'HGBS11': 'Shoppings',
    'XPML11': 'Shoppings',
    'VISC11': 'Shoppings',
    'HSML11': 'Shoppings',
    'CPSH11': 'Shoppings',
    'AJFI11': 'Shoppings',
    'ABCP11': 'Shoppings',
    'BBIG11': 'Shoppings',
    'GSFI11': 'Shoppings',
    'BPML11': 'Shoppings',
    'FIGS11': 'Shoppings',
    'VSHO11': 'Shoppings',
    'FVPQ11': 'Shoppings',
    'PQDP11': 'Shoppings',
    'LASC11': 'Shoppings',
    'SCPF11': 'Shoppings',
    'FLRP11': 'Shoppings',
    'SHPH11': 'Shoppings',
    'VPSI11': 'Shoppings',
    'FIVN11': 'Shoppings',
    'WPLZ11': 'Shoppings',
    'HPDP11': 'Shoppings',
    'ATSA11': 'Shoppings',
    'APXM11': 'Shoppings',
    'FATN11': 'Lajes Corporativas',
    'GTWR11': 'Lajes Corporativas',
    'VINO11': 'Lajes Corporativas',
    'HGRE11': 'Lajes Corporativas',
    'PVBI11': 'Lajes Corporativas',
    'TEPP11': 'Lajes Corporativas',
    'HGPO11': 'Lajes Corporativas',
    'AIEC11': 'Lajes Corporativas',
    'CXCO11': 'Lajes Corporativas',
    'BBFI11': 'Lajes Corporativas',
    'PATC11': 'Lajes Corporativas',
    'KORE11': 'Lajes Corporativas',
    'SPTW11': 'Lajes Corporativas',
    'RCRB11': 'Lajes Corporativas',
    'XPCM11': 'Lajes Corporativas',
    'HOFC11': 'Lajes Corporativas',
    'CNES11': 'Lajes Corporativas',
    'HBCR11': 'Lajes Corporativas',
    'RNGO11': 'Lajes Corporativas',
    'CEOC11': 'Lajes Corporativas',
    'BMLC11': 'Lajes Corporativas',
    'BLCA11': 'Lajes Corporativas',
    'CXCE11': 'Lajes Corporativas',
    'CXCE11B': 'Lajes Corporativas',
    'NEWU11': 'Lajes Corporativas',
    'EDGA11': 'Lajes Corporativas',
    'TSER11': 'Lajes Corporativas',
    'VVCO11': 'Lajes Corporativas',
    'CBOP11': 'Lajes Corporativas',
    'TJKB11': 'Lajes Corporativas',
    'RMAI11': 'Lajes Corporativas',
    'FPAB11': 'Lajes Corporativas',
    'FPNG11': 'Lajes Corporativas',
    'CTXT11': 'Lajes Corporativas',
    'TOPP11': 'Lajes Corporativas',
    'HAAA11': 'Lajes Corporativas',
    'CJCT11': 'Lajes Corporativas',
    'EDFO11': 'Lajes Corporativas',
    'FISC11': 'Lajes Corporativas',
    'EDFO11B': 'Lajes Corporativas',
    'ERPA11': 'Lajes Corporativas',
    'BTWR11': 'Lajes Corporativas',
    'FMOF11': 'Lajes Corporativas',
    'ALMI11': 'Lajes Corporativas',
    'TRNT11': 'Lajes Corporativas',
    'DOVL11B': 'Lajes Corporativas',
    'PRSV11': 'Lajes Corporativas',
    'HDOF11': 'Lajes Corporativas',
    'NEWL11': 'Logística',
    'HSLG11': 'Logística',
    'XPLG11': 'Logística',
    'HGLG11': 'Logística',
    'BTLG11': 'Logística',
    'GARE11': 'Logística', # 'Renda Urbana'
    'SJAU11': 'Logística',
    'TRBL11': 'Logística',
    'RBLG11': 'Logística',
    'RZAT11': 'Logística', # 'Renda Urbana'
    'GGRC11': 'Logística',
    'LVBI11': 'Logística',
    'VILG11': 'Logística',
    'BRCO11': 'Logística',
    'FIIB11': 'Logística',
    'PATL11': 'Logística',
    'INLG11': 'Logística',
    'RBRL11': 'Logística',
    'VTLT11': 'Logística',
    'HGBL11': 'Logística',
    'EURO11': 'Logística',
    'SNLG11': 'Logística',
    'BPRP11': 'Logística',
    'OULG11': 'Logística',
    'CPLG11': 'Logística',
    'HLOG11': 'Logística',
    'PQAG11': 'Logística',
    'GLOG11': 'Logística',
    'CXTL11': 'Logística',
    'DPRO11': 'Logística',
    'PBLV11': 'Logística',
    'GRUL11': 'Logística',
    'RZZR11': 'Logística',
    'HDEL11': 'Logística',
    'AZPL11': 'Logística',
    'BLOG11': 'Logística',
    'CYLD11': 'Logística',
    'GCDL11': 'Logística',
    'RBED11': 'Educacional',
    'FCFL11': 'Educacional',
    'MINT11': 'Educacional',
    'NVHO11': 'Hospitalar',
    'HCRI11': 'Hospitalar',
    'NSLU11': 'Hospitalar',
    'HUSC11': 'Hospitalar',
    'HUCG11': 'Hospitalar',
    'HUSI11': 'Hospitalar',
    'HTMX11': 'Hotéis',
    'MGHT11': 'Hotéis',
    'BTHI11': 'Hotéis',
    'INRD11': 'Residencial',
    'OBAL11': 'Residencial',
    'MXRF11': 'Fundo de Papel',
    'VGHF11': 'Fundo de Papel',
    'KNCR11': 'Fundo de Papel',
    'CPTS11': 'Fundo de Papel',
    'VGIR11': 'Fundo de Papel',
    'BTCI11': 'Fundo de Papel',
    'KNSC11': 'Fundo de Papel',
    'IRDM11': 'Fundo de Papel',
    'HCTR11': 'Fundo de Papel',
    'KNIP11': 'Fundo de Papel',
    'HGCR11': 'Fundo de Papel',
    'RECR11': 'Fundo de Papel',
    'DEVA11': 'Fundo de Papel',
    'RBRR11': 'Fundo de Papel',
    'HABT11': 'Fundo de Papel',
    'VRTA11': 'Fundo de Papel',
    'MCCI11': 'Fundo de Papel',
    'RZAK11': 'Fundo de Papel',
    'CACR11': 'Fundo de Papel',
    'URPR11': 'Fundo de Papel',
    'RBRY11': 'Fundo de Papel',
    'CVBI11': 'Fundo de Papel',
    'PORD11': 'Fundo de Papel',
    'BCRI11': 'Fundo de Papel',
    'XPCI11': 'Fundo de Papel',
    'AFHI11': 'Fundo de Papel',
    'VSLH11': 'Fundo de Papel',
    'GAME11': 'Fundo de Papel',
    'VGIP11': 'Fundo de Papel',
    'CYCR11': 'Fundo de Papel',
    'ARRI11': 'Fundo de Papel',
    'KNHY11': 'Fundo de Papel',
    'MCRE11': 'Fundo de Papel',
    'MCHY11': 'Fundo de Papel',
    'OUJP11': 'Fundo de Papel',
    'VCRI11': 'Fundo de Papel',
    'KCRE11': 'Fundo de Papel',
    'VCJR11': 'Fundo de Papel',
    'BARI11': 'Fundo de Papel',
    'VVCR11': 'Fundo de Papel',
    'SADI11': 'Fundo de Papel',
    'PLCR11': 'Fundo de Papel',
    'KIVO11': 'Fundo de Papel',
    'JPPA11': 'Fundo de Papel',
    'KNUQ11': 'Fundo de Papel',
    'JSAF11': 'Fundo de Papel',
    'BTHF11': 'Fundo de Papel',
    'NCHB11': 'Fundo de Papel',
    'RBHG11': 'Fundo de Papel',
    'NAVT11': 'Fundo de Papel',
    'LFTT11': 'Fundo de Papel',
    'OGIN11': 'Fundo de Papel',
    'LSPA11': 'Fundo de Papel',
    'CLIN11': 'Fundo de Papel',
    'IBCR11': 'Fundo de Papel',
    'RBHY11': 'Fundo de Papel',
    'HSAF11': 'Fundo de Papel',
    'FLCR11': 'Fundo de Papel',
    'HREC11': 'Fundo de Papel',
    'GCRI11': 'Fundo de Papel',
    'IRIM11': 'Fundo de Papel',
    'ICRI11': 'Fundo de Papel',
    'RNDP11': 'Fundo de Papel',
    'RRCI11': 'Fundo de Papel',
    'ITIP11': 'Fundo de Papel',
    'RPRI11': 'Fundo de Papel',
    'HCHG11': 'Fundo de Papel',
    'NCRI11': 'Fundo de Papel',
    'PLRI11': 'Fundo de Papel',
    'EXES11': 'Fundo de Papel',
    'PEMA11': 'Fundo de Papel',
    'VOTS11': 'Fundo de Papel',
    'BICR11': 'Fundo de Papel',
    'PNCR11': 'Fundo de Papel',
    'SAPI11': 'Fundo de Papel',
    'HGIC11': 'Fundo de Papel',
    'ARXD11': 'Fundo de Papel',
    'REIT11': 'Fundo de Papel',
    'WSEC11': 'Fundo de Papel',
    'QAMI11': 'Fundo de Papel',
    'JSCR11': 'Fundo de Papel',
    'SRVD11': 'Fundo de Papel',
    'BLUR11': 'Fundo de Papel',
    'DAMA11': 'Fundo de Papel',
    'PULV11': 'Fundo de Papel',
    'EQIN11': 'Fundo de Papel',
    'HBTT11': 'Fundo de Papel',
    'ZAVC11': 'Fundo de Papel',
    'NPAR11': 'Fundo de Papel',
    'CIXM11': 'Fundo de Papel',
    'RBCB11': 'Fundo de Papel',
    'LKDV11': 'Fundo de Papel',
    'PRZS11': 'Fundo de Papel',
    'RCRI11B': 'Fundo de Papel',
    'RECD11': 'Fundo de Papel',
    'FISD11': 'Fundo de Papel',
    'AGRX11': 'Fiagros',
    'LSAG11': 'Fiagros',
    'NCRA11': 'Fiagros',
    'AAZQ11': 'Fiagros',
    'DCRA11': 'Fiagros',
    'PLCA11': 'Fiagros',
    'OIAG11': 'Fiagros',
    'RURA11': 'Fiagros',
    'XPCA11': 'Fiagros',
    'BBGO11': 'Fiagros',
    'IAAG11': 'Fiagros',
    'EGAF11': 'Fiagros',
    'CPTR11': 'Fiagros',
    'VGIA11': 'Fiagros',
    'RZAG11': 'Fiagros',
    'KNCA11': 'Fiagros',
    'SNAG11': 'Fiagros',
    'FGAA11': 'Fiagros',
    'GCRA11': 'Fiagros',
    'VCRA11': 'Fiagros',
    'BTRA11': 'Fiagros',
    'JGPX11': 'Fiagros',
    'BTAG11': 'Fiagros',
    'CRAA11': 'Fiagros',
    'HGAG11': 'Fiagros',
    'GRWA11': 'Fiagros',
    'IAGR11': 'Fiagros',
    'SNFZ11': 'Fiagros',
    'FZDA11': 'Fiagros',
    'KOPA11': 'Fiagros',
    'RZEO11': 'Fiagros',
    'NEXG11': 'Fiagros',
    'BRFT11': 'Fiagros',
    'VRTM11': 'Fundo de Fundos', # 'Híbrido'
    'DVFF11': 'Fundo de Fundos', # 'Títulos e Val. Mob.'
    'RVBI11': 'Fundo de Fundos',
    'KISU11': 'Fundo de Fundos',
    'RBRF11': 'Fundo de Fundos',
    'XPSF11': 'Fundo de Fundos',
    'HFOF11': 'Fundo de Fundos',
    'KFOF11': 'Fundo de Fundos',
    'RBFF11': 'Fundo de Fundos',
    'BCIA11': 'Fundo de Fundos',
    'RBRX11': 'Fundo de Fundos',
    'SNFF11': 'Fundo de Fundos',
    'ALZM11': 'Fundo de Fundos',
    'HGFF11': 'Fundo de Fundos',
    'BPFF11': 'Fundo de Fundos',
    'VIFI11': 'Fundo de Fundos',
    'OUFF11': 'Fundo de Fundos',
    'CPFF11': 'Fundo de Fundos',
    'BBFO11': 'Fundo de Fundos',
    'ITIT11': 'Fundo de Fundos',
    'CXCI11': 'Fundo de Fundos',
    'CRFF11': 'Fundo de Fundos',
    'RFOF11': 'Fundo de Fundos',
    'CXRI11': 'Fundo de Fundos',
    'BICE11': 'Fundo de Fundos',
    'AFOF11': 'Fundo de Fundos',
    'RCFF11': 'Fundo de Fundos',
    'IFIE11': 'Fundo de Fundos',
    'JCCJ11': 'Fundo de Fundos',
    'XBXO11': 'Fundo de Fundos',
    'JCIN11': 'Fundo de Fundos',
    'QMFF11': 'Fundo de Fundos',
    'FLNR11': 'Fundo de Fundos',
    'MFII11': 'Fundo de Desenvolvimento', # 'Residencial'
    'TGAR11': 'Fundo de Desenvolvimento',
    'KINP11': 'Fundo de Desenvolvimento',
    'BRIM11': 'Fundo de Desenvolvimento',
    'INRD11': 'Fundo de Desenvolvimento',
    'BRIP11': 'Fundo de Desenvolvimento',
    'TRXB11': 'Fundo de Desenvolvimento',
    'LUGG11': 'Fundo de Desenvolvimento',
    'AROA11': 'Fundo de Desenvolvimento',
    'RBTS11': 'Fundo de Desenvolvimento',
    'KEVE11': 'Fundo de Desenvolvimento',
    'HRDF11': 'Fundo de Desenvolvimento',
    'RBIR11': 'Fundo de Desenvolvimento',
    'EGYR11': 'Fundo de Desenvolvimento',
    'RBDS11': 'Fundo de Desenvolvimento',
    'RBRI11': 'Fundo de Desenvolvimento',
    'OBAL11': 'Fundo de Desenvolvimento',
    'BTSI11': 'Fundo de Desenvolvimento',
    'VXXV11': 'Fundo de Desenvolvimento',
    'RCFA11': 'Fundo de Desenvolvimento',
    'CFHI11': 'Fundo de Desenvolvimento',
    'STRX11': 'Fundo de Desenvolvimento',
    'CFII11': 'Fundo de Desenvolvimento',
    'BTWR11': 'Fundo de Desenvolvimento',
    'DMAC11': 'Fundo de Desenvolvimento',
    'ROOF11': 'Fundo de Desenvolvimento',
    'YUFI11': 'Fundo de Desenvolvimento',
    'PNPR11': 'Fundo de Desenvolvimento',
    'PABY11': 'Fundo de Desenvolvimento',
    'RSPD11': 'Fundo de Desenvolvimento',
    'LOFT11B': 'Fundo de Desenvolvimento',
    'ICNE11': 'Fundo de Desenvolvimento',
    'JPPC11': 'Fundo de Desenvolvimento',
    'MMPD11': 'Fundo de Desenvolvimento',
    'HCST11': 'Fundo de Desenvolvimento',
    'LRDI11': 'Fundo de Desenvolvimento',
    'HRES11': 'Fundo de Desenvolvimento',
    'ZIFI11': 'Fundo de Desenvolvimento',
    'ORPD11': 'Fundo de Desenvolvimento',
    'HDOF11': 'Fundo de Desenvolvimento',
    'TELD11': 'Fundo de Desenvolvimento',
    'JTPR11': 'Fundo de Desenvolvimento',
    'ONDV11': 'Fundo de Desenvolvimento',
    'INDE11': 'Fundo de Desenvolvimento',
    'ASRF11': 'Fundo de Desenvolvimento',
    'JURO11': 'FI-Infra',
    'BDIF11': 'FI-Infra',
    'KDIF11': 'FI-Infra',
    'CPTI11': 'FI-Infra',
    'IFRA11': 'FI-Infra',
    'CDII11': 'FI-Infra',
    'BODB11': 'FI-Infra',
    'SNID11': 'FI-Infra',
    'BIDB11': 'FI-Infra',
    'AZIN11': 'FI-Infra',
    'OGIN11': 'FI-Infra',
    'IFRI11': 'FI-Infra',
    'XPID11': 'FI-Infra',
    'NUIF11': 'FI-Infra',
    'RBIF11': 'FI-Infra',
    'KNDI11': 'FI-Infra',
    'BINC11': 'FI-Infra',
    'JMBI11': 'FI-Infra',
    'RIFF11': 'FI-Infra',
    'VANG11': 'FI-Infra',
    'IRIF11': 'FI-Infra',
    'INFB11': 'FI-Infra',
    'BDIV11': 'FIP',
    'VIGT11': 'FIP',
    'XPIE11': 'FIP',
    'PFIN11': 'FIP',
    'BRZP11': 'FIP',
    'PPEI11': 'FIP',
    'KNOX11': 'FIP',
    'PICE11': 'FIP',
    'ESUU11': 'FIP',
    'ENDD11': 'FIP',
    'COPN11': 'FIP',
    'BTAL11': 'Outros',
}